// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif


RcppExport SEXP _rcpp_module_boot_PCMBaseCpp__Tree();
RcppExport SEXP _rcpp_module_boot_PCMBaseCpp__OrderedTree();
RcppExport SEXP _rcpp_module_boot_PCMBaseCpp__QuadraticPolyWhite();
RcppExport SEXP _rcpp_module_boot_PCMBaseCpp__QuadraticPolyBM();
RcppExport SEXP _rcpp_module_boot_PCMBaseCpp__QuadraticPolyBM1D();
RcppExport SEXP _rcpp_module_boot_PCMBaseCpp__QuadraticPolyOU();
RcppExport SEXP _rcpp_module_boot_PCMBaseCpp__QuadraticPolyOU1D();
RcppExport SEXP _rcpp_module_boot_PCMBaseCpp__QuadraticPolyJOU();
RcppExport SEXP _rcpp_module_boot_PCMBaseCpp__QuadraticPolyDOU();
RcppExport SEXP _rcpp_module_boot_PCMBaseCpp__QuadraticPolyMixedGaussian();
RcppExport SEXP _rcpp_module_boot_PCMBaseCpp__QuadraticPolyMixedGaussian1D();
RcppExport SEXP _rcpp_module_boot_PCMBaseCpp__QuadraticPolyEB();
RcppExport SEXP _rcpp_module_boot_PCMBaseCpp__QuadraticPolyEB1D();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_PCMBaseCpp__Tree", (DL_FUNC) &_rcpp_module_boot_PCMBaseCpp__Tree, 0},
    {"_rcpp_module_boot_PCMBaseCpp__OrderedTree", (DL_FUNC) &_rcpp_module_boot_PCMBaseCpp__OrderedTree, 0},
    {"_rcpp_module_boot_PCMBaseCpp__QuadraticPolyWhite", (DL_FUNC) &_rcpp_module_boot_PCMBaseCpp__QuadraticPolyWhite, 0},
    {"_rcpp_module_boot_PCMBaseCpp__QuadraticPolyBM", (DL_FUNC) &_rcpp_module_boot_PCMBaseCpp__QuadraticPolyBM, 0},
    {"_rcpp_module_boot_PCMBaseCpp__QuadraticPolyBM1D", (DL_FUNC) &_rcpp_module_boot_PCMBaseCpp__QuadraticPolyBM1D, 0},
    {"_rcpp_module_boot_PCMBaseCpp__QuadraticPolyOU", (DL_FUNC) &_rcpp_module_boot_PCMBaseCpp__QuadraticPolyOU, 0},
    {"_rcpp_module_boot_PCMBaseCpp__QuadraticPolyOU1D", (DL_FUNC) &_rcpp_module_boot_PCMBaseCpp__QuadraticPolyOU1D, 0},
    {"_rcpp_module_boot_PCMBaseCpp__QuadraticPolyJOU", (DL_FUNC) &_rcpp_module_boot_PCMBaseCpp__QuadraticPolyJOU, 0},
    {"_rcpp_module_boot_PCMBaseCpp__QuadraticPolyDOU", (DL_FUNC) &_rcpp_module_boot_PCMBaseCpp__QuadraticPolyDOU, 0},
    {"_rcpp_module_boot_PCMBaseCpp__QuadraticPolyMixedGaussian", (DL_FUNC) &_rcpp_module_boot_PCMBaseCpp__QuadraticPolyMixedGaussian, 0},
    {"_rcpp_module_boot_PCMBaseCpp__QuadraticPolyMixedGaussian1D", (DL_FUNC) &_rcpp_module_boot_PCMBaseCpp__QuadraticPolyMixedGaussian1D, 0},
    {"_rcpp_module_boot_PCMBaseCpp__QuadraticPolyEB", (DL_FUNC) &_rcpp_module_boot_PCMBaseCpp__QuadraticPolyEB, 0},
    {"_rcpp_module_boot_PCMBaseCpp__QuadraticPolyEB1D", (DL_FUNC) &_rcpp_module_boot_PCMBaseCpp__QuadraticPolyEB1D, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_PCMBaseCppCustom(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
